### ISSUE TITLE
🐛 Client should not send `Access-Control-Origin` in request header

### ISSUE THREAD

**Issue by micedre** [InseeFrLab/sugoi-ui#153]
In requests done by the javascript client we add the `Access-Control-Allow-Origin, this is a response only header, the line should be removed here : https://github.com/InseeFrLab/sugoi-ui/blob/8de77f7b8deebc4627b05d79f153ec6ee76f7dca/src/configuration/utils.tsx#L13

https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

**Comment by ShubhamPalriwala** [comment]
So all one has to do is just remove line 13? :/

**Comment by micedre** [comment]
> So all one has to do is just remove line 13? :/

Yes :) hence the label.
